spring:
  application:
    name: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&serverTimezone=UTC
    username: root
    password:       #密码950
  batch:
    job:
      enabled: false #任务自动执行 关闭
  #      names: parentJob   #父Job名字
  main:
    allow-bean-definition-overriding: true

  #  -------redis配置--------------------------
  redis:
    host:                     #远程主机IP
    port: 6379
    database: 0
    connect-timeout: 1800000  #连接超时时间 毫秒
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1  #最大阻塞等待时间  负数表示没有限制
        max-idle: 5   #连接池最大空闲连接
        min-idle: 0   #最小空闲连接
    password:   #密码
