#------------------------------------------spring--------------------
spring:
  profiles:
    active: local
#  kafka:
#    bootstrap-servers: 主机地址:9092
#
#    producer: # 生产者
#      retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
#      batch-size: 16384
#      buffer-memory: 33554432
#      acks: 1
#      # 指定消息key和消息体的编解码方式
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#    consumer:
#      group-id: default-group
#      enable-auto-commit: false
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#    listener:
#      # 当每一条记录被消费者监听器（ListenerConsumer）处理之后提交
#      # RECORD
#      # 当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后提交
#      # BATCH
#      # 当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后，距离上次提交时间大于TIME时提交
#      # TIME
#      # 当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后，被处理record数量大于等于COUNT时提交
#      # COUNT
#      # TIME |　COUNT　有一个条件满足时提交
#      # COUNT_TIME
#      # 当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后, 手动调用Acknowledgment.acknowledge()后提交
#      # MANUAL
#      # 手动调用Acknowledgment.acknowledge()后立即提交，一般使用这种
#      # MANUAL_IMMEDIATE
#      ack-mode: manual_immediate

#spring:
#  application:
#    name: redis
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
##    url: jdbc:postgresql://localhost:5432/test
##    dbType: postgresql
##    username: postgres
##    password: postgres
##    driver-class-name: org.postgresql.Driver
#
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 9+ab
##password: 9+ab
#
#  elasticsearch:
#    rest:
#      uris: 主机Ip:9200
#      connection-timeout: 2000           #---连接超时时间(默认1s)
#      read-timeout: 6000
#
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#
#mybatisPlus:
#  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#datasource:
#  name: test
#  type: com.alibaba.druid.pool.DruidDataSource
#  url: jdbc:h2:mem:test;MODE=Postgresql
#  dbType: postgresql
#  username: postgres
#  password: postgres
#  driver-class-name: org.postgresql.Driver


#这里的配置会覆盖logback-spring中的日志打印级别
logging:
  level:
    root: info