spring:
  application:
    name: springbatch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&serverTimezone=UTC
    username: root
    password: 919550
  batch:
    job:
      enabled: false #任务自动执行 关闭
  #      names: parentJob   #父Job名字
  main:
    allow-bean-definition-overriding: true

