server:
  port: 8080
#------------------------------------------spring--------------------
spring:
  application:
    name: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/nowcodersql?useSSL=false&serverTimezone=UTC
    username: root
    password: 919550ab

mybatis:
  mapper-locations: classpath*:mapper/*.xml

